Fix: Navigation links scroll to top on click
TeamShiksha/logoexecutive pull request #339
Opened 2024-07-13 00:28 UTC by Asin-Junior-Honore

### Summary

Fixes issue #338.

### Description

Updated `ScrollContext.js` to include a scroll-to-top functionality when navigation links are clicked. This ensures that the user is brought to the top of the new page upon navigation.

### How to Test the Changes

1. Clone the repository and switch to the branch where this PR is made:
   ```bash
   git clone https://github.com/TeamShiksha/logoexecutive.git
   cd logoexecutive
   git checkout <branch-name>
   ```

2. Navigate to the client directory and ensure Yarn is installed and dependencies are up to date:
   ```bash
   cd client
   yarn install
   ```

3. Start the application:
   ```bash
   yarn start
   ```

4. Navigate to any page with scrollable content.
5. Click on any navigation link within the application.
6. Verify that the page scrolls to the top upon navigation.

### Context

The issue occurred when users navigated within the application; the page did not reset to the top, causing a poor user experience. This PR addresses this by implementing a scroll-to-top functionality in `ScrollContext.js`.

### Checklist

- [x] I have tested the changes locally and they work as expected.
- [ ] I have added/updated tests that cover the changes. (Update this once tests are added.)
- [ ] I have updated the documentation to reflect the changes.
- [x] This pull request follows the project's coding guidelines.
```

2024-07-13 13:12 UTC, aps08 requested changes
No test file found for the new file added.

2024-07-13 19:29 UTC, Asin-Junior-Honore commented
Hey 
@aps08 , I have added a test file for the new ScrollContext. Kindly review at your earliest convenience.

2024-07-13 19:43 UTC, aps08 commented
@anandbaraik review this.

2024-07-14 14:05 UTC, anandbaraik commented on client/src/App.js
> +			<ScrollProvider>
Move <ScrollProvider>  component to `index.js` file. Keep all context provider at one place.

2024-07-14 14:06 UTC, anandbaraik commented on client/src/App.js
> +			<ScrollProvider>
> Move component to `index.js` file. Keep all context provider at one place.

@Asin-Junior-Honore

2024-07-14 14:36 UTC, anandbaraik commented
@aps08 looked at the PR, tested locally and navigation links scroll to top are working fine.  Test for ScrollContext is passing. 
@Asin-Junior-Honore, I have added a comment, please take a look and change it.
@samyak269 please review it and once it's fine we can merge. CC: @aps08

2024-07-14 14:41 UTC, Asin-Junior-Honore commented
hey 
@anandbaraik 
thanks for the review, I would implement the requested changes as soon as possible thanks😊

2024-07-14 15:00 UTC, Asin-Junior-Honore commented
hey
@anandbaraik I have made the requested changes. kindly review, thanks😊

2024-07-14 16:23 UTC, aps08 approved these changes

2024-07-14 16:34 UTC, merged

2024-07-14 16:39 UTC, aps08 commented
@Asin-Junior-Honore Changes are deployed and working properly. And it is working fine. Thank you for your contribution.