Implement revert to customer mechanism for Contact Us queries
TeamShiksha/logoexecutive pull request #357
Opened 2024-08-21 21:45 UTC by asharma991

### Summary

Add new route to revert to the customer.

### Description

Adding new route to revert to the customer using new flow for the Contact Us. This is a part of #349.
New controllers and services added have been tested thoroughly and verified in the API client.

### How to Test the Changes

Test the ```/api/operator/revert``` route by using the sample payload and the cookie header with the jwt.

**Sample Payload**:
```bash
curl --location --request PUT 'http://localhost:5000/api/operator/revert' \
--header 'Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImZpcnN0TmFtZSI6IkFiaGlzaGVrIiwibGFzdE5hbWUiOiJTaGFybWEiLCJlbWFpbCI6ImFzaGFybWE5OTFAb3V0bG9vay5jb20iLCJ1c2VySWQiOiI2NmJiYWNkZDE3OGZkZTk2YmY5NGQzZTAiLCJ1c2VyVHlwZSI6Ik9QRVJBVE9SIn0sImlhdCI6MTcyNDI2MDAyMCwiZXhwIjoxNzI0MzQ2NDIwfQ.wWPYJ_gbWjGkKmiYQIzDrmAiZEluDLMYrahtpDx3Smg' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id":"66b8f98b188eab673279035f",
    "email": "ayushsanjpro@gmail.com",
    "reply": "Hi there where are you now"
}'
```

**Happy Response**:
```json
{
    "statusCode": 200,
    "message": "Response sent to customer successfully"
}
```

**Already Replied**
```json
{
    "statusCode": 409,
    "error": "Conflict",
    "message": "Already sent the response for this query!"
}
```

### Changes

A simple controller has been written for reverting and a new service for updating the form is implemented. Few mocks have been added to test the changes.

### Screenshots or Recordings (Optional)

![image](https://github.com/user-attachments/assets/1bf5f0eb-49b9-4061-b1a3-075df1d2fe63)
![image](https://github.com/user-attachments/assets/01401bbb-8d96-47c0-b13f-bef935717bc9)

## Checklist

- [x] I have tested the changes locally and they work as expected.
- [x] I have added/updated tests that cover the changes.
- [x] I have updated the documentation to reflect the changes.
- [x] This pull request follows the project's coding guidelines.

2024-08-29 03:59 UTC, Ayushsanjdev commented
@asharma991 Please merge this in your dev(forked).
and close this PR, we will together raise one PR.

2024-09-13 16:38 UTC, amankumarsingh77 requested changes

2024-09-13 16:38 UTC, amankumarsingh77 commented on server/services/ContactUs.js
> +    const currentForm = await ContactUs.findOne({ _id: formId, email });
Wouldn't it be better to use findById() as _id is an index by default? Also, _id is a unique identifier so I don't think we need email.

2024-09-13 16:39 UTC, asharma991 commented on server/services/ContactUs.js
> +    const currentForm = await ContactUs.findOne({ _id: formId, email });
email is removed in the latest implementation. I'll change it to findById

2024-09-14 17:39 UTC, Ayushsanjdev commented on server/services/ContactUs.js
> +    const currentForm = await ContactUs.findOne({ _id: formId, email });
updated the changes: @amankumarsingh77 @asharma991

2024-09-15 06:30 UTC, amankumarsingh77 approved these changes

2024-09-15 06:52 UTC, merged