Raise request frontend
TeamShiksha/logoexecutive pull request #396
Opened 2024-10-23 19:20 UTC by shantanu-02

### Summary

Authenticated users can raise a request for their company logo by providing their Company url.

Issue ticket number : #395 

### Approach

On home page in Try it now section when user searches for a brand logo and doesn't find one an error message is displayed below as Logo Not Available. Beneath this error message a section to Raise a Request will be added with a message Couldn't find your logo try raising a request and a button Raise a Request. Upon clicking this button a modal will open up which is a form asking for user email Id and company URL. Upon this form submission user's request for their logo is processed.

### How to Test the Changes

Go to home page and searcg for logo. There is no Raise a Request section for user to request their company logo upon failing to find their logo.

### Screenshots or Recordings

<img width="908" alt="TSSS1" src="https://github.com/user-attachments/assets/3921d55e-e073-4acd-b347-b7259e02d788">
<img width="907" alt="TSSS2" src="https://github.com/user-attachments/assets/7db2b6cb-5c04-418c-b4af-5f334f3d7105">
<img width="909" alt="TSSS3" src="https://github.com/user-attachments/assets/d52f3858-7382-4d17-8889-8173d8516a56">

## Checklist

- [x] I have added/updated tests that cover the changes.
- [ ] I have updated the documentation to reflect the changes.

2024-10-23 19:55 UTC, aps08 requested changes
1. Coverage report missing.
2. msw file/tests missing.

2024-10-24 06:19 UTC, Ayushsanjdev commented
Add a coverage report screnshlt in PR of the components file that u worked on and try to make it green.

2024-10-24 06:20 UTC, Ayushsanjdev commented
Add a coverage report screnshot in PR of the components file that u worked on and try to make it green.

Also please fix the sonar cloud issue

2024-10-24 20:56 UTC, shantanu-02 commented
> 1. Coverage report missing.
> 2. msw file/tests missing.

Done with the changes...Please review again

2024-10-25 05:06 UTC, Ayushsanjdev commented
> > 1. Coverage report missing.
> > 2. msw file/tests missing.
> 
> Done with the changes...Please review again
> Sonal cloud issue is not fixed beacuse, brand URL's containing HTTP are also being accepted as a request.
> Let me know if you want to change this condition @aps08 

The coverage that u added is not test coverage, please read about coverage of tests.

2024-10-25 07:14 UTC, shantanu-02 commented
> > > 1. Coverage report missing.
> > > 2. msw file/tests missing.
> > 
> > 
> > Done with the changes...Please review again
> > Sonal cloud issue is not fixed beacuse, brand URL's containing HTTP are also being accepted as a request.
> > Let me know if you want to change this condition @aps08
> 
> The coverage that u added is not test coverage, please read about coverage of tests.

I have read about it...but how should I generate it?...script from the package.json file is not working for client folder.

2024-10-26 05:39 UTC, Ayushsanjdev commented
Like how i told you, try to do like that using coverage command and check if your file is report is good or not, add a screenshot @shantanu-02

2024-10-26 05:48 UTC, Ayushsanjdev requested changes, later dismissed
I will review once you add coverage report and a demo video with ui functionality and test cases

2024-10-26 05:48 UTC, Ayushsanjdev commented on client/src/components/demo/Demo.test.js
> +import {describe, it, expect, vi} from 'vitest'; // Ensure vi is imported
Remove the comment, don't blindly copy from chat gpt

2024-10-26 14:58 UTC, shantanu-02 commented
> Like how i told you, try to do like that using coverage command and check if your file is report is good or not, add a screenshot @shantanu-02

The script in the package.json is configured for Jest, not Vitest, which is why it isn’t working. Should I add the necessary packages and adjust the configuration to generate a coverage report with Vitest?

2024-11-06 18:46 UTC, aps08 approved these changes

2024-11-07 07:41 UTC, VinayakaHegade approved these changes

2024-11-07 09:29 UTC, aps08 commented
@VinayakaHegade can you approve this again.

2024-11-07 09:30 UTC, VinayakaHegade approved these changes

2024-11-07 09:31 UTC, VinayakaHegade commented
> @VinayakaHegade can you approve this again.

Approved.

2024-11-08 16:29 UTC, DeltaDynamo approved these changes

2024-11-08 16:30 UTC, merged