Add cache invalidation
TeamShiksha/logoexecutive pull request #417
Opened 2024-11-18 11:35 UTC by amoghar29

### Summary

This PR implements cache invalidation.

### Approach

In this PR i have added functionality to invalidate cloudFront cache.
Created the cloudFrontInvalidate(paths) function to invalidate the CloudFront cache .
This function takes array of paths as input and sends an invalidation request to CloudFront using the AWS SDK’s CreateInvalidationCommand .

### How to Test the Changes

### Screenshots or Recordings

https://github.com/user-attachments/assets/d6ccc87e-ae90-4dd2-bea4-7311b0379f29

## Checklist

- [ ] I have added/updated tests that cover the changes.
- [ ] I have updated the documentation to reflect the changes.

2024-11-18 16:31 UTC, aps08 commented on server/utils/cloudFront.js
> +  const distributionId = process.env.DISTRIBUTION_ID; // Ensure DISTRIBUTION_ID is set in your environment
use multiline comments at top of the function,

2024-11-18 16:33 UTC, aps08 requested changes
Add it in the reupload option for image for admin.

2024-11-18 17:10 UTC, amoghar29 commented
Have made all the said changes.

2024-11-18 17:17 UTC, aps08 commented on server/controllers/admin/reupload.js
> +    try {
why try catch is here ?

2024-11-18 17:20 UTC, amoghar29 commented on server/controllers/admin/reupload.js
> +    try {
removed.

2024-11-18 17:26 UTC, aps08 approved these changes

2024-11-18 17:27 UTC, aps08 commented
@amoghar29 get is approved by one more person.

2024-11-19 09:07 UTC, DeltaDynamo approved these changes

2024-11-19 09:40 UTC, merged