Usage component dashboard
TeamShiksha/logoexecutive pull request #428
Opened 2024-11-28 22:07 UTC by shantanu-02

### Summary

This PR implements the Usage Component Available on dashboard page as  per the new design.
Issue : #425 

### How to Test the Changes

To test the changes you will have the render the dashboard component from the pages folder.

### Screenshots or Recordings

Expected UI :
<img width="477" alt="image" src="https://github.com/user-attachments/assets/d9b04ef0-4643-40d1-94ea-e89774c9cf9f">

Implemented UI :
![Screenshot (13)](https://github.com/user-attachments/assets/98b96603-3504-41a5-a31b-edca9d630026)

## Checklist

- [x] I have added/updated tests that cover the changes.
- [x] I have updated the documentation to reflect the changes.

2024-12-01 16:48 UTC, aps08 requested changes
resolve conflicts. Use module CSS. Remove test files. Improve the code quality as suggested by sonar cloud.

2024-12-02 16:56 UTC, 001AM commented
I am working on it

2024-12-06 16:23 UTC, aps08 commented
@001AM can you provide latest recording of the UI.

2024-12-09 16:33 UTC, aps08 approved these changes

2024-12-09 16:33 UTC, merged