update: Created new page for privacy policy
TeamShiksha/logoexecutive pull request #458
Opened 2024-12-19 17:43 UTC by 001AM

### Summary

Generated and Create Page for Privacy and Policy.

### Approach
Created Page for Privacy and Policy.

### How to Test the Changes
Visit the Page.

### Screenshots or Recordings
![Screenshot from 2024-12-19 23-10-42](https://github.com/user-attachments/assets/0310791a-b22b-4aa3-a232-5b3dcbd61070)
![Screenshot from 2024-12-19 23-10-54](https://github.com/user-attachments/assets/b559ff91-f0c0-428d-9840-66880f4c60ad)
![Screenshot from 2024-12-19 23-10-58](https://github.com/user-attachments/assets/69019681-2d51-4597-a876-916d2851d1a9)

## Checklist

- [x] I have added/updated tests that cover the changes.
- [x] I have updated the documentation to reflect the changes.

2024-12-19 17:51 UTC, aps08 requested changes
This page contains content which we don't even provide. Example: login with social media. Did you read this ?

2024-12-19 18:01 UTC, 001AM commented
I have read the privacy policy. I know currently project doesn't provide any social media login. I was skeptic about it I thought this will be implemented later on. Also I have doubt about the Tracking Technologies and Cookies should I remove that also.Any more input what should be there and not be present will be more helpful.

2024-12-30 16:59 UTC, aps08 requested changes
Divide them in 3 para.

2024-12-30 16:59 UTC, aps08 commented
Do not add a PR in the project.

2025-01-03 18:28 UTC, aps08 commented
@contains old commits also showing 11 files changes.  Rebase please

2025-01-04 13:16 UTC, closed without merging