Added Docker support
TeamShiksha/logoexecutive pull request #474
Opened 2024-12-28 09:32 UTC by Katsuya21

### Summary

This PR adds docker support to the project. Users can set up the project locally with ease.

### Approach

Added a docker-compose file to the root folder to run both the frontend and backend parallelly.
Added separate Dockerfiles for Frontend and Backend to run them both individually as well.

### How to Test the Changes

Clone the repo. Start Docker daemon and run "docker-compose up -d" in the root of the project to run both frontend and backend parallelly.

### Screenshots or Recordings

https://github.com/user-attachments/assets/1dac6989-f044-45a2-adc4-b99fff947d54

## Checklist

- [ ] I have added/updated tests that cover the changes.
- [ ] I have updated the documentation to reflect the changes.

2024-12-30 16:51 UTC, aps08 commented on packages/ui/vite.config.js
What is this change

2024-12-30 16:52 UTC, aps08 requested changes
Make the suggested changes as per sonarcube. Other than the image root issue as dicussed

2025-01-03 13:16 UTC, Katsuya21 commented on packages/ui/vite.config.js
This enables the Vite Dev server to listen to all network interfaces i.e. it lets the server be accessible from the docker container

2025-01-03 14:18 UTC, aps08 commented
Not like this. If you are instead of `COPY . .`

You had to do `COPY /packages/ui /app` for the front end. Similarly, for backend.

2025-01-03 16:36 UTC, aps08 approved these changes

2025-01-03 16:59 UTC, aps08 approved these changes

2025-01-03 16:59 UTC, merged